# Generated by Django 5.0 on 2025-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='last_daily_card',
            field=models.DateField(blank=True, null=True),
        ),
    ]
