name: Build & Deploy to AKS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # 1) Declare that this job will output a value called "image"
    # Hello
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username:    ${{ secrets.ACR_NAME }}
          password:    ${{ secrets.ACR_PASSWORD }}

      # 2) Build & push – and set the output
      - name: Build & push image
        id: build-image                   # <- give this step an ID
        working-directory: poketrade
        run: |
          IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/poketrade:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          # export IMAGE as a step output called "image"
          echo "::set-output name=image::$IMAGE"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Deploy Deployment & Service
        run: |
          kubectl apply -f poketrade/deployment.yaml
          kubectl apply -f poketrade/service.yaml

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/poketrade --namespace default
